version: '3'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ./db/secret.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db-tiers

  b2-gateway:
    image: minio/minio
    restart: unless-stopped
    command: minio gateway b2
    env_file:
      - ./minio/secret.env
    networks:
      - b2-gateway-tiers

  nextcloud:
    build: ./nextcloud
    restart: unless-stopped
    env_file:
      - ./minio/secret.env
    volumes:
      - nextcloud:/var/www/html
    networks:
      - proxy-tiers
      - db-tiers
      - b2-gateway-tiers
    depends_on:
      - db
      - proxy
      - b2-gateway

  proxy:
    image: abiosoft/caddy:php-no-stats
    build:
      # Required because docker-compose clone from github doesn't work
      # See https://github.com/docker/compose/issues/2856 for more info
      context: proxy/caddy-docker/php
      dockerfile: Dockerfile-no-stats
      args:
        PUID: 82
        PGID: 82
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/Caddyfile:/etc/Caddyfile:ro
      - nextcloud:/var/www/html
      - certs:/root/.caddy
    networks:
      - proxy-tiers

volumes:
  nextcloud:
  certs:
  db:

networks:
  proxy-tiers:
  db-tiers:
  b2-gateway-tiers: